on:
  workflow_call:
    inputs:
      build_type:
        description: "One of: [branch, nightly, pull-request]"
        required: true
        type: string
      branch:
        description: "Git branch the workflow run targets. Used to organize artifacts."
        type: string
      date:
        description: "Date (YYYY-MM-DD) this run is for. Used to organize artifacts produced by nightly builds"
        type: string
      sha:
        description: "Full git commit SHA to check out"
        type: string

permissions:
  actions: read
  contents: read
  id-token: write
  packages: read
  pull-requests: read

jobs:
  compute-matrix:
    uses: rapidsai/shared-workflows/.github/workflows/compute-matrix.yaml@main
    with:
      build_type: ${{ inputs.build_type }}
      matrix_name: conda-cpp-build
  build:
    name: ${{ matrix.CUDA_VER }}, ${{ matrix.PY_VER }}, ${{ matrix.ARCH }}, ${{ matrix.LINUX_VER }}
    needs: compute-matrix
    runs-on: linux-${{ matrix.ARCH }}-cpu16
    env:
      RAPIDS_BUILD_TYPE: ${{ inputs.build_type }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - name: Standardize repository information
        uses: rapidsai/shared-actions/rapids-github-info@main
        with:
          branch: ${{ inputs.branch }}
          date: ${{ inputs.date }}
          sha: ${{ inputs.sha }}
      - uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 10800
      - name: Setup sccache-dist
        uses: rapidsai/shared-actions/setup-sccache-dist@main
        with:
          request-timeout: 7140
      - name: Build standalone C tarball
        env:
          CUVS_TARBALL_CUDA_VERSION: ${{ matrix.CUDA_VER }}
          CUVS_TARBALL_PYTHON_VERSION: ${{ matrix.PY_VER }}
        run: |
          ./build.sh tarball --tarball-build-tests
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: libcuvs_c_${{ matrix.CUDA_VER }}_${{ matrix.ARCH }}.tar.gz
          path: libcuvs_c.tar.gz
